# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.3'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
  weave:
    image: sha256:9953066a4ea0e346fe38c48d16c3bce061e22c28cd9a1a1ceb6808348e77bc25
    container_name: weave
    restart: on-failure
    ports:
      - "20611:20611"
    environment:
      - TZ=PRC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/weave?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - SERVER_PORT=20611
      - OSS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID
      - OSS_ACCESS_KEY_SECRET=YOUR_ACCESS_KEY_SECRET
      - JWT_SECRET=YOUR_JWT_SECRET
      - APP_PASSWORD=Weave123456
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
